extends:
  - eslint:recommended

env:
  es6: true
  node: true
  jest: true

parserOptions:
  sourceType: module

globals:
  document: true
  window: true
  history: true
  jQuery: true
  $: true

rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style: [error, unix]
  quotes: [error, double]
  arrow-parens: [warn, as-needed]
  object-curly-spacing: [warn, always]
  no-multiple-empty-lines:
    - warn
    - max: 1
      maxEOF: 0
  space-before-function-paren:
    - warn
    - anonymous: always
      named: never
      asyncArrow: always
  padding-line-between-statements:
    - warn
    - blankLine: always
      prev: block-like
      next: "*"
    - blankLine: always
      prev: function
      next: "*"
    - blankLine: "always"
      prev: "directive"
      next: "*"

  semi: 2
  eqeqeq: 2
  no-var: 2
  new-parens: 2
  no-loop-func: 2
  arrow-spacing: 2
  no-extra-semi: 2
  no-mixed-spaces-and-tabs: 2

  eol-last: 1
  spaced-comment: 1
  no-multi-spaces: 1
  no-trailing-spaces: 1
  space-before-blocks: 1
  space-infix-ops: 1
  keyword-spacing: 1
  comma-spacing: 1
  key-spacing: 1
  lines-between-class-members: 1

  no-console: 0
  comma-dangle: 0
  space-unary-ops: 0
  array-bracket-spacing: 0
  no-constant-condition: 0
